SampleLeague/src/main/java/com/jobtask/league/model/types/Game.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.model.types;

/**
 *
 * @author dmsj
 */
public enum Game {
    Football,
    Basketball;
}

SampleLeague/src/main/java/com/jobtask/league/model/types/View.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.model.types;

/**
 *
 * @author dmsj
 */
public enum View {
    TEAM_BASKETBALL_10,
    TEAM_FOOTBALL_10,
    LEAGUE_FOOTBALL_10,
    LEAGUE_BASKETBALL_10,
    PLAYER_FOOTBALL_10,
    PLAYER_BASKETBALL_10;
}

SampleLeague/src/main/java/com/jobtask/league/config/StartupBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.config;

import com.jobtask.league.handlers.RankViewHandler;
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.Singleton;
import javax.ejb.Startup;

/**
 *
 * @author dmsj
 */
@Startup
@Singleton
public class StartupBean {

    public enum States {
       STARTED, PAUSED, SHUTTING_DOWN
    };
    private States state;

    @PostConstruct
    public void start() {
        // Perform intialization
        state = States.STARTED;
        System.out.println("<-------------->Application state changed--------->" + getState());
        Config.load();
        RankViewHandler.register();
    }

    @PreDestroy
    public void stop() {
        state = States.SHUTTING_DOWN;
        // Perform termination
        System.out.println("<-------------->Application state changed--------->" + getState());
    }

    public States getState() {
        return state;
    }

    public void setState(States state) {
        this.state = state;
    }
}

SampleLeague/src/main/java/com/jobtask/league/controller/LeagueController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.controller;

import com.jobtask.league.config.Config;
import com.jobtask.league.dao.TeamDao;
import com.jobtask.league.model.League;
import com.jobtask.league.model.Team;
import com.jobtask.league.model.types.Game;
import com.jobtask.league.services.LeagueService;
import com.jobtask.league.util.MessageUtil;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.faces.event.ActionEvent;
import javax.inject.Inject;
import org.primefaces.event.CloseEvent;

/**
 *
 * @author dmsj
 */
@Named(value = "leagueController")
@ViewScoped
public class LeagueController implements Serializable {

    /**
     * Creates a new instance of LeagueController
     */
    @Inject
    private transient LeagueService leagueService;
    @Inject
    private transient TeamDao teamDao;

    private League selectedLeague;
    private League createLeague;
    private List<Team> availableTeams;
    private List<Team> allTeams;
    private Set<Team> selectedTeams;
    private List<League> allLeagues;
    private boolean createDialogOpen;
    private boolean editInProgress;
    private League originalLeague;
    private Map<Integer, Set<Team>> selectedTeamsForUpdate;

    public League getCreateLeague() {
        if (createLeague == null) {
            createLeague = new League();
            createLeague.setEditable(true);
        }
        return createLeague;
    }

    public LeagueController() {
    }

    public boolean isEditInProgress() {
        return editInProgress || createDialogOpen;
    }

    public void setEditInProgress(boolean editInProgress) {
        this.editInProgress = editInProgress;
    }

    public League getSelectedLeague() {
        return selectedLeague;
    }

    public void setSelectedLeague(League selectedLeague) {
        this.selectedLeague = selectedLeague;
    }

    public void setCreateDialogOpened(ActionEvent event) {
        createDialogOpen = true;
    }

    public void setCreateDialogClosed(CloseEvent event) {
        createDialogOpen = false;
    }

    public boolean isCreateDialogOpen() {
        return createDialogOpen;
    }

    public Set<Team> getSelectedTeams() {
        return selectedTeams;
    }

    public void setSelectedTeams(Set<Team> selectedTeams) {
        this.selectedTeams = selectedTeams;
    }

    public League getOriginalLeague() {
        return originalLeague;
    }

    public void setOriginalLeague(League originalLeague) {
        this.originalLeague = originalLeague;
    }

    public List<League> getAllLeagues() {
        return allLeagues;
    }

    public List<Team> getAvailableTeams() {
        return availableTeams;
    }

    public void delete(League league) {
        leagueService.delete(league);
        if (getAllLeagues().contains(league)) {
            getAllLeagues().remove(league);
        }
        MessageUtil.sendInfoMessageToUser("League " + league.getName() + " has been deleted");
    }

    public void updateAvailableTeams(League league) {
        if (league != null) {
            updateAvailableTeams(league.getGame());
        }
    }

    public void updateAvailableTeams(Game game) {
        selectedTeams.clear();
        availableTeams.clear();
        availableTeams.addAll(leagueService.getAvailableTeams(game, allTeams));
    }

    public void updateAvailableTeams() {
        updateAvailableTeams(createDialogOpen ? getCreateLeague() : getSelectedLeague());
    }

    public void changeGame(Game game) {
        if (game == null) {
            return;
        }
        updateAvailableTeams(game);
    }

    public void changeGame() {
        changeGame(selectedLeague.getGame());
    }

    public void addTeam(League league, Team team) {
        if (league.getId() == null) {
            selectedTeams.add(team);
            return;
        }
        int key = league.getId();
        Set<Team> teams = selectedTeamsForUpdate.get(key);
        team.setRemove(false);
        if (teams == null) {
            selectedTeamsForUpdate.put(key, new HashSet<>(Arrays.asList(team)));
        } else if (teams.contains(team)) {
            teams.remove(team);
        } else {
            teams.add(team);
        }
    }

    public void removeTeam(League league, Team team) {
        if (league.getId() == null) {
            selectedTeams.remove(team);
            return;
        }
        int key = league.getId();
        Set<Team> teams = selectedTeamsForUpdate.get(key);
        team.setRemove(true);
        if (teams == null) {
            selectedTeamsForUpdate.put(key, new HashSet<>(Arrays.asList(team)));
        } else if (teams.contains(team)) {
            teams.remove(team);
        } else {
            teams.add(team);
        }
    }

    public String saveUpdate(League league) {
        update(league);
        return "leagues";
    }

    public String save() {
        saveLeague();
        return "leagues";
    }

    public String edit(League league) {
        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("league", league);
        updateAvailableTeams(league);
        FacesContext.getCurrentInstance().getExternalContext().getFlash().put("teams", availableTeams);
        originalLeague = new League(league);
        return "edit_league";
    }

    public void saveLeague() {
        if (!selectedTeams.isEmpty()) {
            getCreateLeague().getTeams().clear();
            getCreateLeague().getTeams().addAll(selectedTeams);
            selectedTeams.clear();
        }
        leagueService.save(getCreateLeague());
        getCreateLeague().setEditable(false);
        MessageUtil.sendInfoMessageToUser(String.format("%s saved", getCreateLeague().getName()));

        //in order to avoid reading from db for renewing entries add new league to leagues list
        if (!getAllLeagues().contains(getCreateLeague())) {
            getAllLeagues().add(getCreateLeague());
        }
    }

    public void editTeams() {
        selectedTeamsForUpdate.clear();
        Set<Team> teams = new HashSet<>(selectedLeague.getTeams());
        originalLeague.setTeams(teams);
    }

    public void cancelEdit() {
        selectedLeague.setEditable(false);
        setEditInProgress(false);
    }

    public void edit() {
        selectedLeague.setEditable(true);
        updateAvailableTeams(selectedLeague);
        setEditInProgress(true);
        setSelectedLeague(selectedLeague);
        originalLeague = new League(selectedLeague);
        //in case if user didn't close teams dialog update edit teams dialog
        editTeams();
    }

    public void update(League league) {
        Set<Team> updateTeams = selectedTeamsForUpdate.get(league.getId());
        Set<Team> remove = null;
        if (originalLeague != null && originalLeague.getGame() != league.getGame()) {
            league.getTeams().clear();
        }
        if (updateTeams != null) {
            remove = new HashSet<>();
            for (Team team : updateTeams) {
                if (team.remove()) {
                    remove.add(team);
                    continue;
                }
                league.getTeams().add(team);
            }
        }
        if (remove != null) {
            league.getTeams().removeAll(remove);
        }

        if (originalLeague != null && leagueService.equals(league, originalLeague)) {
            MessageUtil.sendInfoMessageToUser("Nothing changed");
            return;
        }
        MessageUtil.sendInfoMessageToUser(String.format("%s updated", league.getName()));
        leagueService.update(league);
    }

    public void update() {
        update(selectedLeague);
    }

    public String cancel() {
        return "leagues";
    }

    public String create() {
        createDialogOpen = true;
        return "create_league";
    }

    public void resetFields() {
        selectedTeamsForUpdate.clear();
        createLeague = new League();
        createLeague.setEditable(true);
        selectedTeams.clear();
        availableTeams.clear();
        createDialogOpen = true;
    }

    public Boolean leagueHasTeam(League league, Team team) {

        Set<Team> teams = selectedTeamsForUpdate.get(league.getId());

        if (teams != null) {
            for (Team tm : teams) {
                if (Objects.equals(tm.getId(), team.getId())) {
                    return !tm.remove();
                }
            }
        }
        if (league.isEditable() && selectedTeams.contains(team)) {
            return true;
        }
        return leagueService.leagueHasTeam(league, team);
    }

    @PostConstruct
    public void initResources() {
        allTeams = teamDao.getAllTeams();
        allLeagues = leagueService.getAllLeagues();
        selectedLeague = new League();
        selectedTeams = new HashSet<>();
        selectedTeamsForUpdate = new HashMap<>();
        availableTeams = new ArrayList<>();
        if (Config.FILTER_TEAMS_FOR_LEAGUES) {
            allLeagues.stream().forEach((league) -> {
                leagueService.filterTeams(league);
            });
        }
    }
}

SampleLeague/src/main/java/com/jobtask/league/controller/StatsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.controller;

import com.jobtask.league.config.Config;
import com.jobtask.league.handlers.RankViewHandler;
import com.jobtask.league.model.League;
import com.jobtask.league.model.Player;
import com.jobtask.league.model.Team;
import com.jobtask.league.services.StatsService;
import com.jobtask.league.util.RankingUtil;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import com.jobtask.league.model.types.View;

/**
 *
 * @author dmsj
 */
@Named(value = "statsController")
@ViewScoped
public class StatsController implements Serializable {

    @Inject
    private transient StatsService statsService;
    private String currentView;
    private String viewName;
    private List<Team> basketballTeams;
    private List<Team> footballTeams;
    private List<Player> basketballPlayers;
    private List<Player> footballPlayers;
    private List<League> basketballLeagues;
    private List<League> footballLeagues;

    /**
     * Creates a new instance of StatsController
     */
    public StatsController() {
    }

    public List<Team> getBasketballTeams() {
        return basketballTeams;
    }

    public List<Team> getFootballTeams() {
        return footballTeams;
    }

    public List<Player> getBasketballPlayers() {
        return basketballPlayers;
    }

    public List<Player> getFootballPlayers() {
        return footballPlayers;
    }

    public List<League> getBasketballLeagues() {
        return basketballLeagues;
    }

    public List<League> getFootballLeagues() {
        return footballLeagues;
    }

    public String getCurrentView() {
        return currentView;
    }

    public void setCurrentView(View view) {
        resolveCurrentViewName(view);
        this.currentView = RankViewHandler.getView(view);
    }

    public String getViewName() {
        return viewName;
    }

    private void resolveCurrentViewName(View top) {
        switch (top) {
            case TEAM_BASKETBALL_10:
                viewName = "Top basketball teams";
                break;
            case TEAM_FOOTBALL_10:
                viewName = "Top football teams";
                break;
            case LEAGUE_FOOTBALL_10:
                viewName = "Top football leagues";
                break;
            case LEAGUE_BASKETBALL_10:
                viewName = "Top basketball leagues";
                break;
            case PLAYER_FOOTBALL_10:
                viewName = "Top football players";
                break;
            case PLAYER_BASKETBALL_10:
                viewName = "Top basketball players";
                break;
        }
    }

    @PostConstruct
    public void init() {
        //initialize teams
        basketballTeams = statsService.getBasketballTeams();
        footballTeams = statsService.getFootballTeams();
        //calculate teams score (players score sum)
        statsService.resolveTotalPlayersScore(basketballTeams);
        statsService.resolveTotalPlayersScore(footballTeams);
        //when players score sum are attached to teams time to sort and reslove ranks
        RankingUtil.resolveTeamsByScore(basketballTeams, true, Config.LIMIT_TEAMS);
        RankingUtil.resolveTeamsByAverageScore(footballTeams, true, Config.LIMIT_TEAMS);

        //initialize players
        basketballPlayers = statsService.getBasketballPlayers();
        footballPlayers = statsService.getFootballPlayers();
        //sort limit and resolve ranks for football players
        RankingUtil.resolvePlayersByAverageScore(footballPlayers, true, Config.LIMIT_PLAYERS);
        //list should be already limited and sorted so just resolve ranks
        RankingUtil.resolvePlayersByScore(basketballPlayers, false, 0);

        //initialize leagues
        basketballLeagues = statsService.getBasketballLeagues();
        footballLeagues = statsService.getFootballLeagues();
        statsService.resolveTotalTeamsScore(basketballLeagues);
        statsService.resolveAverageScore(footballLeagues);
        RankingUtil.resolveLeaguesByScore(basketballLeagues, true, Config.LIMIT_LEAGUES);
        RankingUtil.resolveLeaguesByAverageScore(footballLeagues, true, Config.LIMIT_LEAGUES);
        //set default view
        setCurrentView(View.TEAM_BASKETBALL_10);
    }
}

SampleLeague/src/main/java/com/jobtask/league/util/BasicUtilBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jobtask.league.util;

import com.jobtask.league.model.types.Game;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.inject.Named;
import javax.enterprise.context.ApplicationScoped;

/**
 *
 * @author dmsj
 */
@Named(value = "basicUtil")
@ApplicationScoped
public class BasicUtilBean {

    /**
     * Creates a new instance of BasicUtilBean
     */
    public BasicUtilBean() {
    }

    public Game[] getGames() {
        return Game.values();
    }

    public List<Game> getGames(Game exclude) {
        return Arrays.stream(Game.values()).filter(g -> !g.equals(exclude)).collect(Collectors.toList());
    }

}

SampleLeague/src/main/webapp/views/create_league.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/templates/common.xhtml">	
            <ui:define name="content">
                <div id="table-container">
                    <h:form>
                        <h1><h:outputText value="Create league"/></h1>
                        <p:panelGrid class="panel-grid" columns="2">
                            <p:outputLabel value="Name:" for="name" />
                            <p:inputText id="name" value="#{leagueController.createLeague.name}" title="Name" required="true" requiredMessage="The Name field is required."/>
                            <p:outputLabel value="Game:" for="game" />
                            <p:selectOneMenu id="game" value="#{leagueController.createLeague.game}" style="width:150px">
                                <f:selectItem itemLabel="Select Game" itemValue="" noSelectionOption="true"/>
                                <f:selectItems value="#{basicUtil.games}" var="selectedGame" />
                                <p:ajax listener="#{leagueController.updateAvailableTeams(leagueController.createLeague)}" update="add-teams-btn,teams-form" />
                            </p:selectOneMenu>
                            <p:outputLabel for="add-teams-btn" value="Add team"/>
                            <p:commandButton id="add-teams-btn" disabled="#{leagueController.createLeague.game==null}" update="teams-form" oncomplete="PF('teams-dlg').show();" icon="ui-icon-plus"/>
                        </p:panelGrid>
                        <p:commandButton value="Save" ajax="false" action="#{leagueController.save()}"/>
                        <p:link value="Canel" outcome="leagues" />
                    </h:form>
                </div>
                <!--Teams dialog-->
                <p:dialog id="teams-dialog" closable="true" header="Teams" widgetVar="teams-dlg" height="auto" width="auto">
                    <h:form id="teams-form">
                        <c:set var="league" value="#{leagueController.createLeague}" scope="request" />
                        <p:dataTable id="teams-table" value="#{leagueController.availableTeams}" var="team">
                            <p:column headerText="Game">
                                <h:outputText  value="#{team.game}"/>
                            </p:column>
                            <p:column headerText="Name">
                                <h:outputText  value="#{team.name}"/>
                            </p:column>
                            <p:column headerText="Played Games">
                                <h:outputText  value="#{team.playedGames}"/>
                            </p:column>
                            <p:column>
                                <p:commandButton rendered="#{not leagueController.leagueHasTeam(league,team)}" value="Add" action="#{leagueController.addTeam(league,team)}" ajax="true" update="teams-table" process="@this"/>
                                <p:commandButton rendered="#{leagueController.leagueHasTeam(league,team)}" value="Delete" action="#{leagueController.removeTeam(league,team)}" ajax="true" update="teams-table" process="@this"/>
                            </p:column>
                        </p:dataTable>
                        <p:commandButton value="Close" styleClass="ui-confirmdialog-no" onclick="PF('teams-dlg').hide();"/>
                    </h:form>
                </p:dialog>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/create_player.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/templates/common.xhtml">	
            <ui:define name="content">
                <div id="table-container">
                    <h:form>
                        <h1><h:outputText value="Create"/></h1>
                        <p:messages id="messages"/>
                        <p:panelGrid class="panel-grid" columns="2">
                            <p:outputLabel value="Game:" for="game" />
                            <p:selectOneMenu id="game" value="#{playerController.player.game}" required="true" requiredMessage="The Game field is required.">
                                <f:selectItems value="#{basicUtil.games}"/>
                                <p:ajax listener="#{playerController.selectedGameChanged(playerController.player)}" update="team,position"/>
                            </p:selectOneMenu>
                            <p:outputLabel value="PlayedGames:" for="playedGames" />
                            <p:inputText id="playedGames" value="#{playerController.player.playedGames}" title="PlayedGames" />
                            <p:outputLabel value="LastName:" for="lastName" />
                            <p:inputText id="lastName" value="#{playerController.player.lastName}" title="LastName" required="true" requiredMessage="The LastName field is required."/>
                            <p:outputLabel value="Name:" for="name" />
                            <p:inputText id="name" value="#{playerController.player.name}" title="Name" required="true" requiredMessage="The Name field is required."/>
                            <p:outputLabel value="Position:" for="position" />
                            <p:selectOneMenu id="position" value="#{playerController.player.position}" required="true" requiredMessage="The Position field is required.">
                                <f:selectItems value="#{playerController.player.availablePositions}" var="pos" itemLabel="#{pos.name}" itemValue="#{pos}"/>
                            </p:selectOneMenu>
                            <p:outputLabel value="Score:" for="score" />
                            <p:inputText id="score" value="#{playerController.player.score}" title="Score" />
                            <p:outputLabel value="Team:" for="team" />
                            <p:selectOneMenu id="team" value="#{playerController.player.team}" required="true" requiredMessage="The Team field is required.">
                                <f:selectItems value="#{playerController.player.availableTeams}" var="t" itemLabel="#{t.name}" itemValue="#{t}"/>
                            </p:selectOneMenu>
                        </p:panelGrid>
                        <p:commandButton value="Save" ajax="false" action="#{playerController.save()}"/>
                        <p:link value="Cancel" outcome="players"/>
                    </h:form>
                </div>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/create_team.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/templates/common.xhtml">	
            <ui:define name="content">
                <div id="table-container">
                    <h:form>
                        <h1><h:outputText value="Create"/></h1>
                        <p:panelGrid class="panel-grid" columns="2">
                            <p:outputLabel value="Name:" for="name" />
                            <p:inputText id="name" value="#{teamController.newTeam.name}" title="Name" required="true" requiredMessage="The Name field is required."/>
                            <p:outputLabel value="PlayedGames:" for="playedGames" />
                            <p:inputText id="playedGames" value="#{teamController.newTeam.playedGames}" title="PlayedGames" />
                            <p:outputLabel for="add-league-btn" value="Add Leagues"/>
                            <p:commandButton id="add-league-btn" disabled="#{teamController.newTeam.game==null}" update=":leagues-form:" oncomplete="PF('leagues-dlg').show();" icon="ui-icon-plus"/>
                            <p:outputLabel for="gameType" value="Game"/>
                            <p:selectOneMenu id="gameType" value="#{teamController.newTeam.game}" style="width:150px">
                                <f:selectItem itemLabel="Select Game" itemValue="" noSelectionOption="true"/>
                                <f:selectItems value="#{basicUtil.games}" var="selectedGame" />
                                <p:ajax listener="#{teamController.updateAvailableLeagues(teamController.newTeam)}" update="leagues-form:leagues-table,add-league-btn" process="@this" />
                            </p:selectOneMenu>
                        </p:panelGrid>
                        <p:commandButton value="Save" ajax="false" action="#{teamController.save()}"/>
                        <p:link value="Cancel" outcome="teams"/>
                    </h:form>
                </div>
                <!--Leagues dialog-->
                <p:dialog id="leagues-dialog" header="Leagues" widgetVar="leagues-dlg" height="auto" width="auto">
                    <h:form id="leagues-form">
                        <h1><h:outputText value="Leagues"/></h1>
                        <p:dataTable id="leagues-table" value="#{teamController.availableLeagues}" var="item">
                            <p:column headerText="Game">
                                <h:outputText value="#{item.game}"/>
                            </p:column>
                            <p:column headerText="Name">
                                <h:outputText value="#{item.name}"/>
                            </p:column>
                            <p:column>
                                <p:commandButton value="Add" action="#{teamController.addLeague(teamController.newTeam,item)}" rendered="#{not teamController.teamHasLeague(teamController.newTeam,item)}" update="leagues-table"/>
                                <p:commandButton value="Delete" action="#{teamController.removeLeague(teamController.newTeam,item)}" rendered="#{teamController.teamHasLeague(teamController.newTeam,item)}" update="leagues-table" process="@this"/>
                            </p:column>
                        </p:dataTable>
                        <p:commandButton value="Close" onclick="PF('leagues-dlg').hide();"/>
                    </h:form>
                </p:dialog>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/stats.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="/WEB-INF/templates/common.xhtml">
            <ui:define name="content">
                <h:form>
                    <nav id="ranks-menu-horizontal">
                        <ul>
                            <f:ajax render=":current-view">
                                <li id="ft-tm"><h:commandLink value="Top Football teams" action="#{statsController.setCurrentView('TEAM_FOOTBALL_10')}"/></li>            
                                <li id="bk-tm"><h:commandLink value="Top Basketball teams" action="#{statsController.setCurrentView('TEAM_BASKETBALL_10')}"/></li> 
                                <li id="ft-lg"><h:commandLink value="Top Football leagues" action="#{statsController.setCurrentView('LEAGUE_FOOTBALL_10')}" /></li>            
                                <li id="bk-lg"><h:commandLink value="Top Basketball leagues" action="#{statsController.setCurrentView('LEAGUE_BASKETBALL_10')}"/></li> 
                                <li id="ft-pl"><h:commandLink value="Top Football players" action="#{statsController.setCurrentView('PLAYER_FOOTBALL_10')}" /></li>            
                                <li id="bk-pl"><h:commandLink value="Top Basketball players" action="#{statsController.setCurrentView('PLAYER_BASKETBALL_10')}"/></li> 
                            </f:ajax>
                        </ul>
                    </nav>
                </h:form>
                <h:panelGroup id="current-view" layout="block">  
                    <ui:include  src="#{statsController.currentView}" />
                </h:panelGroup>
            </ui:define>
        </ui:composition>
    </h:body>
</html>