SampleLeague/src/main/java/com/jobtask/league/model/Team.java
package com.jobtask.league.model;
// Generated Mar 23, 2016 8:57:25 PM by Hibernate Tools 4.3.1

import com.jobtask.league.model.types.Game;
import java.util.LinkedHashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "teams", catalog = "demo_league"
)
public class Team implements java.io.Serializable {

    private Integer id;
    private Game game;
    private Set<League> leagues = new LinkedHashSet<>(0);
    @NotNull
    @Size(min = 3, max = 28)
    private String name;
    private Integer playedGames;
    private Set<Player> players = new LinkedHashSet<>(0);
    private boolean remove;
    private boolean editable;
    private int totalScore;
    private String rank;

    public Team() {
    }

    public Team(Game game, String name) {
        this.game = game;
        this.name = name;
    }

    public Team(Team team) {
        id = team.getId();
        name = team.getName();
        game = team.getGame();
        playedGames = team.getPlayedGames();
    }

    public Team(Game game, Set<League> leagues, String name, Integer playedGames, Set<Player> players) {
        this.game = game;
        this.leagues = leagues;
        this.name = name;
        this.playedGames = playedGames;
        this.players = players;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "game", nullable = false)
    public Game getGame() {
        return this.game;
    }

    public void setGame(Game game) {
        this.game = game;
    }

    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE}, targetEntity = League.class)
    @JoinTable(name = "leagues_teams", joinColumns = {
        @JoinColumn(name = "teams_id", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "leagues_id", nullable = false, updatable = false)})
    public Set<League> getLeagues() {
        return this.leagues;
    }

    public void setLeagues(Set<League> leagues) {
        this.leagues = leagues;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "played_games")
    public Integer getPlayedGames() {
        return this.playedGames;
    }

    public void setPlayedGames(Integer playedGames) {
        this.playedGames = playedGames;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "team")
    public Set<Player> getPlayers() {
        return this.players;
    }

    public void setPlayers(Set<Player> players) {
        this.players = players;
    }

    public boolean remove() {
        return remove;
    }

    public void setRemove(boolean remove) {
        this.remove = remove;
    }

    @Transient
    public boolean isEditable() {
        return editable;
    }

    public void setEditable(boolean editable) {
        this.editable = editable;
    }

    @Transient
    public int getTotalPlayersScore() {
        return totalScore;
    }

    public void setTotalScore(int score) {
        totalScore = score;
    }

    @Transient
    public double getAverageScore() {
        if (playedGames == 0) {
            return 0;
        }
        return totalScore / playedGames;
    }

    @Transient
    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Team)) {
            return false;
        }
        return Objects.equals(id, ((Team) object).getId());
    }
}

SampleLeague/src/main/webapp/views/tops/top10_league_basketball.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.basketballLeagues}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="League">
                        <h:outputText value="#{item.name}"/>
                    </p:column>
                    <p:column headerText="Total score">
                        <h:outputText value="#{item.totalScore}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/tops/top10_league_football.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.footballLeagues}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="League">
                        <h:outputText value="#{item.name}"/>
                    </p:column>
                    <p:column headerText="Average score">
                        <h:outputText value="#{item.averageScore}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/tops/top10_player_basketball.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.basketballPlayers}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="Player">
                        <h:outputText value="#{item.name}"/>&nbsp;
                        <h:outputText value="#{item.lastName}"/>
                    </p:column>
                    <p:column headerText="Team">
                        <h:outputText value="#{item.team.name}"/>
                    </p:column>
                    <p:column headerText="Leagues">
                        <p:accordionPanel activeIndex="null" multiple="true">
                            <p:tab title="">
                                <ui:repeat var="l" value="#{item.team.leagues.toArray()}">
                                    <h:outputText value="#{l.name}"/><br/>
                                </ui:repeat>
                            </p:tab>
                        </p:accordionPanel>
                    </p:column>
                    <p:column headerText="Score">
                        <h:outputText value="#{item.score}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/tops/top10_player_football.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.footballPlayers}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="Player">
                        <h:outputText value="#{item.name}"/>&nbsp;
                        <h:outputText value="#{item.lastName}"/>
                    </p:column>
                    <p:column headerText="Team">
                        <h:outputText value="#{item.team.name}"/>
                    </p:column>
                    <p:column headerText="Leagues">
                        <p:accordionPanel activeIndex="null" multiple="true">
                            <p:tab title="">
                                <ui:repeat var="l" value="#{item.team.leagues.toArray()}">
                                    <h:outputText value="#{l.name}"/><br/>
                                </ui:repeat>
                            </p:tab>
                        </p:accordionPanel>
                    </p:column>
                    <p:column headerText="Average score">
                        <h:outputText value="#{item.averageScore}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/tops/top10_team_basketball.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.basketballTeams}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="Name">
                        <h:outputText value="#{item.name}"/>
                    </p:column>
                    <p:column headerText="Leagues">
                        <p:accordionPanel activeIndex="null" multiple="true">
                            <p:tab title="">
                                <ui:repeat var="l" value="#{item.leagues.toArray()}">
                                    <h:outputText value="#{l.name}"/><br/>
                                </ui:repeat>
                            </p:tab>
                        </p:accordionPanel>
                    </p:column>
                    <p:column headerText="Total players score">
                        <h:outputText value="#{item.totalPlayersScore}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>

SampleLeague/src/main/webapp/views/tops/top10_team_football.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="#{statsController.viewName}"/></h1>
                <p:dataTable value="#{statsController.footballTeams}" var="item">
                    <p:column headerText="#">
                        <h:outputText value="#{item.rank}"/>
                    </p:column>
                    <p:column headerText="Name">
                        <h:outputText value="#{item.name}"/>
                    </p:column>
                    <p:column headerText="Leagues">
                        <p:accordionPanel activeIndex="null" multiple="true">
                            <p:tab title="">
                                <ui:repeat var="l" value="#{item.leagues.toArray()}">
                                    <h:outputText value="#{l.name}"/><br/>
                                </ui:repeat>
                            </p:tab>
                        </p:accordionPanel>
                    </p:column>
                    <p:column headerText="Average score">
                        <h:outputText value="#{item.averageScore}"/>
                    </p:column>
                </p:dataTable>
            </h:form>
        </f:view>
    </h:body>
</html>